AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
Metrics/ClassLength:
  Exclude:
    - 'spec/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'